/* IMPORTANT INSTRUCTIONS FOR LEARNERS
1) DO NOT CHANGE THE ORDER OF COLUMNS.
2) YOUR QUERY SHOULD DISPLAY COLUMNS IN THE SAME ORDER AS MENTIONED IN ALL QUESTIONS.
3) YOU CAN FIND THE ORDER OF COLUMNS IN QUESTION TEMPLATE SECTION OF EACH QUESTION.
4) USE ALIASING AS MENTIONED IN QUESTION TEMPLATE FOR ALL COLUMNS
5) DO NOT CHANGE COLUMN NAMES*/
                   
-- Question 1 (Marks: 3)
-- Objective: Determine, for flights that actually departed later than scheduled, what the departure delay is (in minutes).
-- Calculate the Delay in Departures for Delayed Flights
-- Question Template: Display following columns flight_id, flight_no, departure_delay_minutes

select  flight_id, flight_no,timestampdiff(minute, scheduled_departure, actual_departure) as departure_delay_minutes
FROM flights
where status = 'Arrived'
and actual_departure > scheduled_departure;

-- Question 2 (Marks: 3)
-- Objective: Show how frequently each aircraft is used by counting the number of flights operated by each aircraft.
-- List Flights Grouped by Aircraft to See Usage Frequency
-- Question Template: Display following columns aircraft_code, total_flights, avg_flight_duration_minutes

select aircraft_code,
COUNT(*) as total_flights,avg(timestampdiff(minute, actual_departure, actual_arrival)) as average_flight_duration_minutes
from flights
where actual_departure is not null 
and actual_arrival is not null
group by aircraft_code;

-- Question 3 (Marks: 3)
-- Objective: Aggregate the total revenue generated by each flight by summing up the fare amounts from the ticket_flights table.
-- Calculate Total Revenue per Flight from the Ticket_Flights Table
-- Question Template: Display following columns flight_id, flight_no, total_revenue

select tf.flight_id,f.flight_no,
sum(tf.amount) as total_revenue
from ticket_flights tf
join flights f on tf.flight_id = f.flight_id
group by tf.flight_id, f.flight_no;

-- Question 4 (Marks: 3)
-- Objective: Examine boarding pass data to identify how passengers are being boarded by calculating the average boarding number per flight.
-- Analyze Boarding Numbers per Flight to Detect Patterns in Boarding Pass Allocation
-- Question Template: Display following columns flight_id, avg_boarding_no, total_boarding_passes

select flight_id, avg(boarding_no) as avg_boarding_no,COUNT(ticket_no) as total_boarding_passes
from boarding_passes
group by flight_id;

-- Question 5 (Marks: 3)
-- Objective: Identify seat occupancy by comparing the number of boarding passes (occupied seats) to the total seats available on an aircraft.
-- Determine Occupancy per Aircraft
-- Question Template: Display following columns flight_id, flight_no, aircraft_code, total_seats, occupied_seats, occupancy_rate_percentage

select f.flight_id,f.flight_no,f.aircraft_code,ts.total_seats,os.occupied_seats,
round((os.occupied_seats * 100.0) / ts.total_seats, 2) as occupancy_rate_percentage
from flights f
join (select aircraft_code,
count(seat_no) as total_seats
from seats
group by aircraft_code) ts on f.aircraft_code = ts.aircraft_code
left join (select flight_id,
count(ticket_no) as occupied_seats
from ticket_flights
group by flight_id) os on f.flight_id = os.flight_id
limit 100;

-- Question 6 (Marks: 3)
-- Objective: Identify the three flights that generated the highest revenue based on ticket sales.
-- Top 3 Flights by Revenue
-- Question Template: Display following columns flight_id, flight_no, total_revenue

select tf.flight_id,f.flight_no,
sum(tf.amount) as total_revenue
from ticket_flights tf
join flights f on tf.flight_id = f.flight_id
group by tf.flight_id, f.flight_no
order by total_revenue DESC
limit 3;

-- Question 7 (Marks: 3)
-- Objective: Determine the average flight duration for each aircraft model, allowing you to see how flight performance might vary between different models.
-- Average Flight Duration by Aircraft Model
-- Question Template: Display following columns model, avg_duration_minutes

select a.model,
round(avg(timestampdiff(MINUTE, f.actual_departure, f.actual_arrival)), 2) as avg_duration_minutes
from flights f
join aircrafts a on f.aircraft_code = a.aircraft_code
where f.actual_departure is not null
and f.actual_arrival is not null
group by a.model;

-- Question 8 (Marks: 3)
-- Objective: Count how many flights depart from each airport to assess airport activity levels.
-- Flight Count per Airport (Departure)
-- Question Template: Display following columns departure_airport, departure_flights

select departure_airport,
COUNT(flight_id) as departure_flights
from flights
group by departure_airport
order by departure_flights DESC;

-- Question 9 (Marks: 3)
-- Objective: Count how many flights depart from and arrive at each airport to assess airport activity levels.
-- Flight Count per Airport (Arrival)
-- Question Template: Display following columns arrival_airport, arrival_flights

select airport,
sum(departure_count) as departure_flights,
sum(arrival_count) as arrival_flights
from 
    (select departure_airport as airport,
	count(*) as departure_count,0 as arrival_count
    from flights
    group by departure_airport
    union all
    select arrival_airport as airport,
	0 as departure_count,
	count(*) as arrival_count
    from flights
    group by arrival_airport) as airport_counts
group by airport
order by (sum(departure_count) + sum(arrival_count)) desc;


-- Question 10 (Marks: 3)
-- Objective: Analyze trends in bookings over time by grouping bookings by date, counting total bookings, and summing up the revenue.
-- Daily Booking Trends
-- Question Template: Display following columns booking_date, total_bookings, total_revenue

select book_date as booking_date,
count(book_ref) as total_bookings,
sum(total_amount) as total_revenue
from bookings
group by book_date
order by book_date;

-- Question 11 (Marks: 3)
-- Objective: Identify the most common routes by counting the number of flights for each departure–arrival airport pair.
-- Frequent Routes Analysis
-- Question Template: Display following columns departure_airport, arrival_airports, flights_count

select departure_airport,arrival_airport,
count(flight_id) as flights_count
from flights
group by departure_airport, arrival_airport
order by flights_count DESC;

-- Question 12 (Marks: 3)
-- Objective: Determine how many passengers boarded each flight by counting the boarding passes issued.
-- Passenger Boarding Summary per Flight
-- Question Template: Display following columns flight_id, passengers_boarded

select flight_id,
count(ticket_no) as passengers_boarded
from ticket_flights
group by flight_id
order by passengers_boarded DESC;

-- Question 13 (Marks: 3)
-- Objective: Assess the boarding process by calculating the average boarding order number for each flight, which may indicate the boarding strategy or sequence.
-- Average Boarding Number per Flight
-- Question Template: Display following columns flight_id, avg_boarding_no

select flight_id,
round(avg(boarding_no), 2) as avg_boarding_no
from boarding_passes
group by flight_id
order by avg_boarding_no DESC;

-- Question 14 (Marks: 3)
-- Objective: Aggregate the total amount spent by each passenger across all their tickets by joining the tickets and ticket_flights tables.
-- Total Spend per Passenger
-- Question Template: Display following columns passenger_id, total_tickets, total_spent

select t.passenger_id,
count(tf.ticket_no) as total_tickets,sum(tf.amount) as total_spent
from tickets t
join ticket_flights tf on t.ticket_no = tf.ticket_no
group by t.passenger_id
order by total_spent DESC;

-- Question 15 (Marks: 3)
-- Objective: Analyze the distribution of ticket volume and revenue across different fare conditions.
-- Fare?Condition Distribution
-- Question Template: Display following columns fare_conditions, tickets_sold, total_revenue

select fare_conditions,
count(ticket_no) as tickets_sold,sum(amount) as total_revenue
from ticket_flights
group by fare_conditions
order by total_revenue DESC;

-- Question 16 (Marks: 3)
-- Objective: Aggregate total revenue generated by each departure?arrival airport route.
-- Revenue by Route
-- Question Template: Display following columns departure_airport, arrival_airport, total_route_revenue

select f.departure_airport,f.arrival_airport,
sum(tf.amount) as total_route_revenue
from ticket_flights tf
join flights f on tf.flight_id = f.flight_id
group by f.departure_airport, f.arrival_airport
order by total_route_revenue DESC;

-- Question 17 (Marks: 2)
-- Objective: Identify the top 5 booking hours of the day by volume of bookings
-- Peak Booking Hours
-- Question Template: Display following columns booking_hour, bookings_count

select 
extract(hour from book_date) as booking_hour,
count(*) as bookings_count
from bookings
group by booking_hour
order by bookings_count DESC
limit 5;
